
// This file was automatically generated by the Dapper.FastCRUD T4 Template
// Do not make changes directly to this file - edit the template configuration instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `Gdp.Mdlp.Data.Properties.Settings.MdlpConnectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=SQLSERVERA3\SRVHARMON;Initial Catalog=Mdlp;Integrated Security=True`
//     Include Views:          `False`

namespace Gdp.Mdlp.Data
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the TaskUnpackHighLevelContainerSscc table.
    /// </summary>
	[Table("TaskUnpackHighLevelContainerSscc")]
	public partial class TaskUnpackHighLevelContainerSscc
	{
		[Key]
	    public virtual string SubjectId { get; set; }
		[Key]
	    public virtual string HighLevelSscc { get; set; }
	    public virtual long? UnpackEventId { get; set; }
	    public virtual string UnpackRequestId { get; set; }
	    public virtual string State { get; set; }
	}

    /// <summary>
    /// A class which represents the Params table.
    /// </summary>
	[Table("Params")]
	public partial class Param
	{
		[Key]
	    public virtual string Id { get; set; }
	    public virtual string Value { get; set; }
	}

    /// <summary>
    /// A class which represents the IncomeDocuments table.
    /// </summary>
	[Table("IncomeDocuments")]
	public partial class IncomeDocument
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long IncomeId { get; set; }
	    public virtual string ClientId { get; set; }
	    public virtual string RequestId { get; set; }
	    public virtual string DocumentId { get; set; }
	    public virtual DateTime? DT { get; set; }
	    public virtual string SenderId { get; set; }
	    public virtual string SysId { get; set; }
	    public virtual string DocType { get; set; }
	    public virtual string DocStatus { get; set; }
	    public virtual int? FileUploadType { get; set; }
	    public virtual string SenderSysId { get; set; }
	    public virtual string Version { get; set; }
	    public virtual byte DocumentStateId { get; set; }
	    public virtual DateTime? ProcessDT { get; set; }
	    public virtual int? DownloadAttempts { get; set; }
	    public virtual DateTime? DownloadAttemptLastDT { get; set; }
	    public virtual DateTime? DownloadAttemptFirstDT { get; set; }
	    public virtual DateTime CreateDT { get; set; }
	    public virtual DateTime? UpdateDT { get; set; }
	    public virtual string CreateUser { get; set; }
	    public virtual string UpdateUser { get; set; }
	}

    /// <summary>
    /// A class which represents the Tickets table.
    /// </summary>
	[Table("Tickets")]
	public partial class Ticket
	{
		[Key]
	    public virtual string RequestId { get; set; }
		[Key]
	    public virtual long EventId { get; set; }
	    public virtual string DocumentId { get; set; }
	    public virtual string ActionId { get; set; }
	}

    /// <summary>
    /// A class which represents the TicketKizInfos table.
    /// </summary>
	[Table("TicketKizInfos")]
	public partial class TicketKizInfo
	{
		[Key]
	    public virtual string RequestId { get; set; }
		[Key]
	    public virtual long EventId { get; set; }
	    public virtual string DocumentId { get; set; }
	    public virtual bool? Found { get; set; }
	    public virtual string Sgtin { get; set; }
	    public virtual string Gtin { get; set; }
	    public virtual string Status { get; set; }
	    public virtual string SeriesNumber { get; set; }
	    public virtual DateTime? ExpirationDate { get; set; }
	    public virtual string Sscc { get; set; }
	    public virtual int? Level { get; set; }
	    public virtual string SsccUp { get; set; }
	    public virtual string SsccDown { get; set; }
	}

    /// <summary>
    /// A class which represents the ProcessFlagOwners table.
    /// </summary>
	[Table("ProcessFlagOwners")]
	public partial class ProcessFlagOwner
	{
		[Key]
	    public virtual byte ProcessFlagNo { get; set; }
	    public virtual string OwnerName { get; set; }
	}

    /// <summary>
    /// A class which represents the IncomeAcceptNotifications table.
    /// </summary>
	[Table("IncomeAcceptNotifications")]
	public partial class IncomeAcceptNotification
	{
		[Key]
	    public virtual long IncomeId { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string CounterpartyId { get; set; }
	    public virtual DateTime? OperationDT { get; set; }
	}

    /// <summary>
    /// A class which represents the EventTypes table.
    /// </summary>
	[Table("EventTypes")]
	public partial class EventType
	{
		[Key]
	    public virtual byte EventTypeId { get; set; }
	    public virtual string Name { get; set; }
	    public virtual byte Priority { get; set; }
	}

    /// <summary>
    /// A class which represents the EventAccepts table.
    /// </summary>
	[Table("EventAccepts")]
	public partial class EventAccept
	{
		[Key]
	    public virtual long EventId { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string CounterpartyId { get; set; }
	    public virtual DateTime? OperationDT { get; set; }
	    public virtual string AcceptedActionId { get; set; }
	}

    /// <summary>
    /// A class which represents the TicketOperations table.
    /// </summary>
	[Table("TicketOperations")]
	public partial class TicketOperation
	{
		[Key]
	    public virtual string RequestId { get; set; }
		[Key]
	    public virtual long EventId { get; set; }
	    public virtual string DocumentId { get; set; }
	    public virtual string Operation { get; set; }
	    public virtual string OperationId { get; set; }
	    public virtual string OperationResult { get; set; }
	    public virtual DateTime? AcceptTime { get; set; }
	    public virtual string OperationComment { get; set; }
	}

    /// <summary>
    /// A class which represents the EventAcceptDetails table.
    /// </summary>
	[Table("EventAcceptDetails")]
	public partial class EventAcceptDetail
	{
		[Key]
	    public virtual long EventId { get; set; }
		[Key]
	    public virtual int DetailNo { get; set; }
	    public virtual string Sgtin { get; set; }
	    public virtual string Sscc { get; set; }
	}

    /// <summary>
    /// A class which represents the IncomeAcceptNotificationDetails table.
    /// </summary>
	[Table("IncomeAcceptNotificationDetails")]
	public partial class IncomeAcceptNotificationDetail
	{
		[Key]
	    public virtual long IncomeId { get; set; }
		[Key]
	    public virtual int RowNo { get; set; }
	    public virtual string Sscc { get; set; }
	    public virtual string Sgtin { get; set; }
	}

    /// <summary>
    /// A class which represents the EventShippings table.
    /// </summary>
	[Table("EventShippings")]
	public partial class EventShipping
	{
		[Key]
	    public virtual long EventId { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string ReceiverId { get; set; }
	    public virtual DateTime? OperationDT { get; set; }
	    public virtual string DocNo { get; set; }
	    public virtual DateTime DocDT { get; set; }
	    public virtual byte? SourceType { get; set; }
	    public virtual byte? TurnoverType { get; set; }
	    public virtual byte? ContractType { get; set; }
	    public virtual string ContractNo { get; set; }
	}

    /// <summary>
    /// A class which represents the IncomeMoveOrders table.
    /// </summary>
	[Table("IncomeMoveOrders")]
	public partial class IncomeMoveOrder
	{
		[Key]
	    public virtual long IncomeId { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string ReceiverId { get; set; }
	    public virtual DateTime? OperationDT { get; set; }
	    public virtual string DocNo { get; set; }
	    public virtual DateTime? DocDT { get; set; }
	    public virtual byte? SourceType { get; set; }
	    public virtual byte? TurnoverType { get; set; }
	    public virtual byte? ContractType { get; set; }
	    public virtual string ContractNo { get; set; }
	}

    /// <summary>
    /// A class which represents the OutcomeDocuments table.
    /// </summary>
	[Table("OutcomeDocuments")]
	public partial class OutcomeDocument
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long OutcomeId { get; set; }
	    public virtual string DocumentId { get; set; }
	    public virtual string RequestId { get; set; }
	    public virtual DateTime? DT { get; set; }
	    public virtual string SenderId { get; set; }
	    public virtual string SysId { get; set; }
	    public virtual string DocType { get; set; }
	    public virtual string DocStatus { get; set; }
	    public virtual int? FileUploadType { get; set; }
	    public virtual string Version { get; set; }
	    public virtual byte DocumentStateId { get; set; }
	    public virtual DateTime? ProcessDT { get; set; }
	    public virtual int? DownloadAttempts { get; set; }
	    public virtual DateTime? DownloadAttemptLastDT { get; set; }
	    public virtual DateTime? DownloadAttemptFirstDT { get; set; }
	    public virtual DateTime CreateDT { get; set; }
	    public virtual DateTime? UpdateDT { get; set; }
	    public virtual string CreateUser { get; set; }
	    public virtual string UpdateUser { get; set; }
	    public virtual string ClientId { get; set; }
	}

    /// <summary>
    /// A class which represents the EventShippingDetails table.
    /// </summary>
	[Table("EventShippingDetails")]
	public partial class EventShippingDetail
	{
		[Key]
	    public virtual long EventId { get; set; }
		[Key]
	    public virtual int DetailNo { get; set; }
	    public virtual decimal Cost { get; set; }
	    public virtual decimal VatValue { get; set; }
	    public virtual string SeriesNumber { get; set; }
	    public virtual string Gtin { get; set; }
	    public virtual string Sgtin { get; set; }
	    public virtual string Sscc { get; set; }
	}

    /// <summary>
    /// A class which represents the IncomeReceiveOrders table.
    /// </summary>
	[Table("IncomeReceiveOrders")]
	public partial class IncomeReceiveOrder
	{
		[Key]
	    public virtual long IncomeId { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string ShipperId { get; set; }
	    public virtual DateTime? OperationDT { get; set; }
	    public virtual string DocNo { get; set; }
	    public virtual DateTime? DocDT { get; set; }
	    public virtual byte? SourceType { get; set; }
	    public virtual byte? ReceiveType { get; set; }
	    public virtual byte? ContractType { get; set; }
	    public virtual string ContractNo { get; set; }
	}

    /// <summary>
    /// A class which represents the OutcomeDocumentStates table.
    /// </summary>
	[Table("OutcomeDocumentStates")]
	public partial class OutcomeDocumentState
	{
		[Key]
	    public virtual byte DocumentStateId { get; set; }
	    public virtual string Name { get; set; }
	}

    /// <summary>
    /// A class which represents the IncomeMoveOrderSsccDetails table.
    /// </summary>
	[Table("IncomeMoveOrderSsccDetails")]
	public partial class IncomeMoveOrderSsccDetail
	{
		[Key]
	    public virtual long IncomeId { get; set; }
		[Key]
	    public virtual int DetailNo { get; set; }
		[Key]
	    public virtual string Sscc { get; set; }
		[Key]
	    public virtual int DetailNo2 { get; set; }
	    public virtual decimal? Cost { get; set; }
	    public virtual decimal? VatValue { get; set; }
	    public virtual string SeriesNumber { get; set; }
	    public virtual string Gtin { get; set; }
	}

    /// <summary>
    /// A class which represents the EventReceipingDetails table.
    /// </summary>
	[Table("EventReceipingDetails")]
	public partial class EventReceipingDetail
	{
		[Key]
	    public virtual long EventId { get; set; }
		[Key]
	    public virtual int DetailNo { get; set; }
	    public virtual decimal Cost { get; set; }
	    public virtual decimal VatValue { get; set; }
	    public virtual string SeriesNumber { get; set; }
	    public virtual string Gtin { get; set; }
	    public virtual string Sgtin { get; set; }
	    public virtual string Sscc { get; set; }
	}

    /// <summary>
    /// A class which represents the IncomeMoveOrderDetails table.
    /// </summary>
	[Table("IncomeMoveOrderDetails")]
	public partial class IncomeMoveOrderDetail
	{
		[Key]
	    public virtual long IncomeId { get; set; }
		[Key]
	    public virtual int DetailNo { get; set; }
	    public virtual decimal? Cost { get; set; }
	    public virtual decimal? VatValue { get; set; }
	    public virtual string Sgtin { get; set; }
	    public virtual string Sscc { get; set; }
	}

    /// <summary>
    /// A class which represents the EventRefusalSenders table.
    /// </summary>
	[Table("EventRefusalSenders")]
	public partial class EventRefusalSender
	{
		[Key]
	    public virtual long EventId { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string ReceiverId { get; set; }
	    public virtual string Reason { get; set; }
	    public virtual DateTime? OperationDT { get; set; }
	}

    /// <summary>
    /// A class which represents the EventReceipings table.
    /// </summary>
	[Table("EventReceipings")]
	public partial class EventReceiping
	{
		[Key]
	    public virtual long EventId { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string ShipperId { get; set; }
	    public virtual DateTime? OperationDT { get; set; }
	    public virtual string DocNo { get; set; }
	    public virtual DateTime DocDT { get; set; }
	    public virtual byte? SourceType { get; set; }
	    public virtual byte? ReceiveType { get; set; }
	    public virtual byte? ContractType { get; set; }
	    public virtual string ContractNo { get; set; }
	}

    /// <summary>
    /// A class which represents the SSCCStates table.
    /// </summary>
	[Table("SSCCStates")]
	public partial class SSCCState
	{
		[Key]
	    public virtual byte State { get; set; }
	    public virtual string Name { get; set; }
	}

    /// <summary>
    /// A class which represents the EventRefusalSenderDetails table.
    /// </summary>
	[Table("EventRefusalSenderDetails")]
	public partial class EventRefusalSenderDetail
	{
		[Key]
	    public virtual long EventId { get; set; }
		[Key]
	    public virtual int DetailNo { get; set; }
	    public virtual string Sgtin { get; set; }
	    public virtual string Sscc { get; set; }
	}

    /// <summary>
    /// A class which represents the IncomeReceiveOrderSsccDetails table.
    /// </summary>
	[Table("IncomeReceiveOrderSsccDetails")]
	public partial class IncomeReceiveOrderSsccDetail
	{
		[Key]
	    public virtual long IncomeId { get; set; }
		[Key]
	    public virtual int DetailNo { get; set; }
		[Key]
	    public virtual string Sscc { get; set; }
		[Key]
	    public virtual int DetailNo2 { get; set; }
	    public virtual decimal? Cost { get; set; }
	    public virtual decimal? VatValue { get; set; }
	    public virtual string SeriesNumber { get; set; }
	    public virtual string Gtin { get; set; }
	}

    /// <summary>
    /// A class which represents the SSCCs table.
    /// </summary>
	[Table("SSCCs")]
	public partial class SSCC
	{
		[Key]
	    public virtual string Sscc { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual byte State { get; set; }
	    public virtual DateTime CreateDT { get; set; }
	    public virtual DateTime? UpdateDT { get; set; }
	    public virtual string CreateUser { get; set; }
	    public virtual string UpdateUser { get; set; }
	    public virtual string ParentSscc { get; set; }
	    public virtual bool? IsUnpackRequested { get; set; }
	    public virtual bool? IsUnpacked { get; set; }
	}

    /// <summary>
    /// A class which represents the Shippings table.
    /// </summary>
	[Table("Shippings")]
	public partial class Shipping
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long ShippingId { get; set; }
	    public virtual string DocNo { get; set; }
	    public virtual DateTime DocDT { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string ReceiverId { get; set; }
	    public virtual DateTime? OperationDT { get; set; }
	    public virtual byte? SourceType { get; set; }
	    public virtual byte? TurnoverType { get; set; }
	    public virtual byte? ContractType { get; set; }
	    public virtual string ContractNo { get; set; }
	    public virtual bool Accepted { get; set; }
	    public virtual DateTime CreateDT { get; set; }
	    public virtual DateTime? UpdateDT { get; set; }
	    public virtual string CreateUser { get; set; }
	    public virtual string UpdateUser { get; set; }
	}

    /// <summary>
    /// A class which represents the IncomeReceiveOrderDetails table.
    /// </summary>
	[Table("IncomeReceiveOrderDetails")]
	public partial class IncomeReceiveOrderDetail
	{
		[Key]
	    public virtual long IncomeId { get; set; }
		[Key]
	    public virtual int DetailNo { get; set; }
	    public virtual decimal? Cost { get; set; }
	    public virtual decimal? VatValue { get; set; }
	    public virtual string Sgtin { get; set; }
	    public virtual string Sscc { get; set; }
	}

    /// <summary>
    /// A class which represents the SGTINStates table.
    /// </summary>
	[Table("SGTINStates")]
	public partial class SGTINState
	{
		[Key]
	    public virtual byte State { get; set; }
	    public virtual string Name { get; set; }
	}

    /// <summary>
    /// A class which represents the SGTINs table.
    /// </summary>
	[Table("SGTINs")]
	public partial class SGTIN
	{
		[Key]
	    public virtual string Sgtin { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual byte State { get; set; }
	    public virtual DateTime CreateDT { get; set; }
	    public virtual DateTime? UpdateDT { get; set; }
	    public virtual string CreateUser { get; set; }
	    public virtual string UpdateUser { get; set; }
	    public virtual string ParentSscc { get; set; }
	    public virtual string Gtin { get; set; }
	    public virtual string SeriesNumber { get; set; }
	    public virtual DateTime? ExpirationDate { get; set; }
	}

    /// <summary>
    /// A class which represents the TaskQueryKizSscc table.
    /// </summary>
	[Table("TaskQueryKizSscc")]
	public partial class TaskQueryKizSscc
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long TaskId { get; set; }
	    public virtual string Sscc { get; set; }
	    public virtual long? EventIdSsccUp { get; set; }
	    public virtual long? EventIdSsccDown { get; set; }
	    public virtual long? IncomeId { get; set; }
	    public virtual bool IsProcessed { get; set; }
	}

    /// <summary>
    /// A class which represents the Receipings table.
    /// </summary>
	[Table("Receipings")]
	public partial class Receiping
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long ReceipingId { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string ShipperId { get; set; }
	    public virtual DateTime? OperationDT { get; set; }
	    public virtual string DocNo { get; set; }
	    public virtual DateTime DocDT { get; set; }
	    public virtual byte? SourceType { get; set; }
	    public virtual byte? ReceiveType { get; set; }
	    public virtual byte? ContractType { get; set; }
	    public virtual string ContractNo { get; set; }
	    public virtual bool Accepted { get; set; }
	    public virtual DateTime CreateDT { get; set; }
	    public virtual DateTime? UpdateDT { get; set; }
	    public virtual string CreateUser { get; set; }
	    public virtual string UpdateUser { get; set; }
	}

    /// <summary>
    /// A class which represents the ReceipingDetails table.
    /// </summary>
	[Table("ReceipingDetails")]
	public partial class ReceipingDetail
	{
		[Key]
	    public virtual long ReceipingId { get; set; }
		[Key]
	    public virtual int DetailNo { get; set; }
	    public virtual decimal Cost { get; set; }
	    public virtual decimal VatValue { get; set; }
	    public virtual string SeriesNumber { get; set; }
	    public virtual string Gtin { get; set; }
	    public virtual string Sgtin { get; set; }
	    public virtual string Sscc { get; set; }
	    public virtual bool Accepted { get; set; }
	}

    /// <summary>
    /// A class which represents the IncomeRefusalSenderNotifications table.
    /// </summary>
	[Table("IncomeRefusalSenderNotifications")]
	public partial class IncomeRefusalSenderNotification
	{
		[Key]
	    public virtual long IncomeId { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string ReceiverId { get; set; }
	    public virtual string Reason { get; set; }
	    public virtual DateTime? OperationDT { get; set; }
	}

    /// <summary>
    /// A class which represents the Locks table.
    /// </summary>
	[Table("Locks")]
	public partial class Lock
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long LockId { get; set; }
	    public virtual long ChildEventId { get; set; }
	    public virtual long OwnerEventId { get; set; }
	    public virtual DateTime CreateDT { get; set; }
	    public virtual string CreateUser { get; set; }
	}

    /// <summary>
    /// A class which represents the LogProcessIncomeMoveOrder table.
    /// </summary>
	[Table("LogProcessIncomeMoveOrder")]
	public partial class LogProcessIncomeMoveOrder
	{
		[Key]
	    public virtual long IncomeId { get; set; }
		[Key]
	    public virtual long EventId { get; set; }
	    public virtual DateTime? CreateDT { get; set; }
	    public virtual string CreateUsr { get; set; }
	}

    /// <summary>
    /// A class which represents the IncomeRefusalSenderNotificationDetails table.
    /// </summary>
	[Table("IncomeRefusalSenderNotificationDetails")]
	public partial class IncomeRefusalSenderNotificationDetail
	{
		[Key]
	    public virtual long IncomeId { get; set; }
		[Key]
	    public virtual int DetailNo { get; set; }
	    public virtual string Sgtin { get; set; }
	    public virtual string Sscc { get; set; }
	}

    /// <summary>
    /// A class which represents the LogProcessIncomeReceiveOrder table.
    /// </summary>
	[Table("LogProcessIncomeReceiveOrder")]
	public partial class LogProcessIncomeReceiveOrder
	{
		[Key]
	    public virtual long IncomeId { get; set; }
		[Key]
	    public virtual long EventId { get; set; }
	    public virtual DateTime? CreateDT { get; set; }
	    public virtual string CreateUsr { get; set; }
	}

    /// <summary>
    /// A class which represents the IncomeRefusalReceiverNotificationDetails table.
    /// </summary>
	[Table("IncomeRefusalReceiverNotificationDetails")]
	public partial class IncomeRefusalReceiverNotificationDetail
	{
		[Key]
	    public virtual long IncomeId { get; set; }
		[Key]
	    public virtual int DetailNo { get; set; }
	    public virtual string Sgtin { get; set; }
	    public virtual string Sscc { get; set; }
	}

    /// <summary>
    /// A class which represents the IncomeRefusalReceiverNotifications table.
    /// </summary>
	[Table("IncomeRefusalReceiverNotifications")]
	public partial class IncomeRefusalReceiverNotification
	{
		[Key]
	    public virtual long IncomeId { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string ShipperId { get; set; }
	    public virtual string Reason { get; set; }
	    public virtual DateTime? OperationDT { get; set; }
	}

    /// <summary>
    /// A class which represents the EventIncomeDocument table.
    /// </summary>
	[Table("EventIncomeDocument")]
	public partial class EventIncomeDocument
	{
		[Key]
	    public virtual long EventId { get; set; }
	    public virtual long IncomeId { get; set; }
	    public virtual string DocType { get; set; }
	}

    /// <summary>
    /// A class which represents the FolderUpdateDTs table.
    /// </summary>
	[Table("FolderUpdateDTs")]
	public partial class FolderUpdateDT
	{
		[Key]
	    public virtual string ClientId { get; set; }
		[Key]
	    public virtual string Folder { get; set; }
	    public virtual DateTime DT { get; set; }
	}

    /// <summary>
    /// A class which represents the IncomeReceiveOrderErrors table.
    /// </summary>
	[Table("IncomeReceiveOrderErrors")]
	public partial class IncomeReceiveOrderError
	{
		[Key]
	    public virtual long IncomeId { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string ShipperId { get; set; }
	    public virtual DateTime? OperationDT { get; set; }
	}

    /// <summary>
    /// A class which represents the IncomePostingNotifications table.
    /// </summary>
	[Table("IncomePostingNotifications")]
	public partial class IncomePostingNotification
	{
		[Key]
	    public virtual long IncomeId { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string Inn { get; set; }
	    public virtual string OrgName { get; set; }
	    public virtual string OwnerId { get; set; }
	    public virtual DateTime? OperationDT { get; set; }
	}

    /// <summary>
    /// A class which represents the IncomeReceiveOrderErrorDetails table.
    /// </summary>
	[Table("IncomeReceiveOrderErrorDetails")]
	public partial class IncomeReceiveOrderErrorDetail
	{
		[Key]
	    public virtual long IncomeId { get; set; }
		[Key]
	    public virtual int DetailNo { get; set; }
	    public virtual string ErrorCode { get; set; }
	    public virtual string ErrorDesc { get; set; }
	    public virtual string ObjectId { get; set; }
	}

    /// <summary>
    /// A class which represents the ShippingDetails table.
    /// </summary>
	[Table("ShippingDetails")]
	public partial class ShippingDetail
	{
		[Key]
	    public virtual long ShippingId { get; set; }
		[Key]
	    public virtual int DetailNo { get; set; }
	    public virtual decimal Cost { get; set; }
	    public virtual decimal VatValue { get; set; }
	    public virtual string SeriesNumber { get; set; }
	    public virtual string Gtin { get; set; }
	    public virtual string Sgtin { get; set; }
	    public virtual string Sscc { get; set; }
	    public virtual bool Accepted { get; set; }
	}

    /// <summary>
    /// A class which represents the IncomePostingNotificationDetails table.
    /// </summary>
	[Table("IncomePostingNotificationDetails")]
	public partial class IncomePostingNotificationDetail
	{
		[Key]
	    public virtual long IncomeId { get; set; }
		[Key]
	    public virtual int DetailNo { get; set; }
	    public virtual string Sgtin { get; set; }
	    public virtual string Sscc { get; set; }
	}

    /// <summary>
    /// A class which represents the Branches table.
    /// </summary>
	[Table("Branches")]
	public partial class Branch
	{
		[Key]
	    public virtual string Id { get; set; }
	    public virtual string SystemSubjId { get; set; }
	    public virtual string Address { get; set; }
	    public virtual int? Status { get; set; }
	}

    /// <summary>
    /// A class which represents the TicketOperationErrors table.
    /// </summary>
	[Table("TicketOperationErrors")]
	public partial class TicketOperationError
	{
		[Key]
	    public virtual string RequestId { get; set; }
		[Key]
	    public virtual long EventId { get; set; }
		[Key]
	    public virtual int ErrorNo { get; set; }
	    public virtual int? error_code { get; set; }
	    public virtual string object_id { get; set; }
	    public virtual string error_desc { get; set; }
	}

    /// <summary>
    /// A class which represents the SafeWarehouses table.
    /// </summary>
	[Table("SafeWarehouses")]
	public partial class SafeWarehous
	{
		[Key]
	    public virtual string Id { get; set; }
	    public virtual string SystemSubjId { get; set; }
	    public virtual string Address { get; set; }
	    public virtual int? Status { get; set; }
	}

    /// <summary>
    /// A class which represents the EventUnpacks table.
    /// </summary>
	[Table("EventUnpacks")]
	public partial class EventUnpack
	{
		[Key]
	    public virtual long EventId { get; set; }
	    public virtual DateTime? OperationDT { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string Sscc { get; set; }
	}

    /// <summary>
    /// A class which represents the EventTicketOperations table.
    /// </summary>
	[Table("EventTicketOperations")]
	public partial class EventTicketOperation
	{
		[Key]
	    public virtual long EventId { get; set; }
	    public virtual string ParentRequestId { get; set; }
	    public virtual long ParentEventId { get; set; }
	    public virtual string Operation { get; set; }
	}

    /// <summary>
    /// A class which represents the EventAcceptNotifications table.
    /// </summary>
	[Table("EventAcceptNotifications")]
	public partial class EventAcceptNotification
	{
		[Key]
	    public virtual long EventId { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string CounterpartyId { get; set; }
	    public virtual DateTime? OperationDT { get; set; }
	}

    /// <summary>
    /// A class which represents the TaskRegistrationUpdates table.
    /// </summary>
	[Table("TaskRegistrationUpdates")]
	public partial class TaskRegistrationUpdate
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long TaskId { get; set; }
	    public virtual DateTime? OpExecStartDT { get; set; }
	    public virtual DateTime? OpExecEndDT { get; set; }
	    public virtual string ClientId { get; set; }
	    public virtual string SystemSubjId { get; set; }
	    public virtual DateTime? CreateDT { get; set; }
	}

    /// <summary>
    /// A class which represents the EventAcceptNotificationSSCCs table.
    /// </summary>
	[Table("EventAcceptNotificationSSCCs")]
	public partial class EventAcceptNotificationSSCC
	{
		[Key]
	    public virtual long EventId { get; set; }
		[Key]
	    public virtual int RowNo { get; set; }
	    public virtual string Sscc { get; set; }
	}

    /// <summary>
    /// A class which represents the EventQueryKiz table.
    /// </summary>
	[Table("EventQueryKiz")]
	public partial class EventQueryKiz
	{
		[Key]
	    public virtual long EventId { get; set; }
	    public virtual DateTime OperationDT { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string Sgtin { get; set; }
	    public virtual string SsccDown { get; set; }
	    public virtual string SsccUp { get; set; }
	}

    /// <summary>
    /// A class which represents the EventAcceptNotificationSGTINs table.
    /// </summary>
	[Table("EventAcceptNotificationSGTINs")]
	public partial class EventAcceptNotificationSGTIN
	{
		[Key]
	    public virtual long EventId { get; set; }
		[Key]
	    public virtual int RowNo { get; set; }
	    public virtual string Sgtin { get; set; }
	}

    /// <summary>
    /// A class which represents the Events table.
    /// </summary>
	[Table("Events")]
	public partial class Event
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long EventId { get; set; }
	    public virtual byte EventTypeId { get; set; }
	    public virtual DateTime CreateDT { get; set; }
	    public virtual DateTime? UpdateDT { get; set; }
	    public virtual string CreateUser { get; set; }
	    public virtual string UpdateUser { get; set; }
	    public virtual int LockCount { get; set; }
	    public virtual int ProcessFlag0 { get; set; }
	    public virtual int ProcessFlag1 { get; set; }
	    public virtual int ProcessFlag2 { get; set; }
	    public virtual int ProcessFlag3 { get; set; }
	    public virtual int ProcessFlag4 { get; set; }
	    public virtual int ProcessFlag5 { get; set; }
	    public virtual byte EventStateId { get; set; }
	    public virtual byte? Priority { get; set; }
	}

    /// <summary>
    /// A class which represents the Registrations table.
    /// </summary>
	[Table("Registrations")]
	public partial class Registration
	{
		[Key]
	    public virtual string SystemSubjId { get; set; }
	    public virtual string OrgName { get; set; }
	    public virtual string Inn { get; set; }
	    public virtual string Kpp { get; set; }
	    public virtual string Ogrn { get; set; }
	    public virtual string FirstName { get; set; }
	    public virtual string MiddleName { get; set; }
	    public virtual string LastName { get; set; }
	    public virtual string CountryCode { get; set; }
	    public virtual string FederalSubjectCode { get; set; }
	}

    /// <summary>
    /// A class which represents the IncomeDocumentStates table.
    /// </summary>
	[Table("IncomeDocumentStates")]
	public partial class IncomeDocumentState
	{
		[Key]
	    public virtual byte DocumentStateId { get; set; }
	    public virtual string Name { get; set; }
	}

    /// <summary>
    /// A class which represents the ClientAddresses table.
    /// </summary>
	[Table("ClientAddresses")]
	public partial class ClientAddress
	{
		[Key]
	    public virtual string ClientId { get; set; }
		[Key]
	    public virtual string SubjectId { get; set; }
	    public virtual string AddressDescription { get; set; }
	    public virtual string ClientName { get; set; }
	    public virtual DateTime CreateDT { get; set; }
	    public virtual DateTime? UpdateDT { get; set; }
	    public virtual string CreateUser { get; set; }
	    public virtual string UpdateUser { get; set; }
	}

    /// <summary>
    /// A class which represents the TicketKizInfoTreeInfos table.
    /// </summary>
	[Table("TicketKizInfoTreeInfos")]
	public partial class TicketKizInfoTreeInfo
	{
		[Key]
	    public virtual string RequestId { get; set; }
		[Key]
	    public virtual long EventId { get; set; }
		[Key]
	    public virtual int NodeNo { get; set; }
	    public virtual string Sscc { get; set; }
	    public virtual string Sgtin { get; set; }
	    public virtual string Gtin { get; set; }
	    public virtual string Status { get; set; }
	    public virtual string SeriesNumber { get; set; }
	    public virtual DateTime? ExpirationDate { get; set; }
	    public virtual string ParentSscc { get; set; }
	}

    /// <summary>
    /// A class which represents the EventQueryHierarchyInfos table.
    /// </summary>
	[Table("EventQueryHierarchyInfos")]
	public partial class EventQueryHierarchyInfo
	{
		[Key]
	    public virtual long EventId { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string Sscc { get; set; }
	}

    /// <summary>
    /// A class which represents the RequestStates table.
    /// </summary>
	[Table("RequestStates")]
	public partial class RequestState
	{
		[Key]
	    public virtual byte RequestStateId { get; set; }
	    public virtual string Name { get; set; }
	}

    /// <summary>
    /// A class which represents the Requests table.
    /// </summary>
	[Table("Requests")]
	public partial class Request
	{
		[Key]
	    public virtual string RequestId { get; set; }
		[Key]
	    public virtual long EventId { get; set; }
	    public virtual string DocumentId { get; set; }
	    public virtual string DocumentState { get; set; }
	    public virtual DateTime CreateDT { get; set; }
	    public virtual DateTime? UpdateDT { get; set; }
	    public virtual string CreateUser { get; set; }
	    public virtual string UpdateUser { get; set; }
	    public virtual byte RequestStateId { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual byte SequenceId { get; set; }
	    public virtual string ActionId { get; set; }
	    public virtual byte? Priority { get; set; }
	    public virtual DateTime? DocumentSentDT { get; set; }
	    public virtual int? TicketDownloadAttempts { get; set; }
	    public virtual int? QueryReusingRecoverAttempts { get; set; }
	    public virtual DateTime? TickedDownloadFirstDT { get; set; }
	    public virtual DateTime? TickedDownloadLastDT { get; set; }
	    public virtual DateTime? QueryReusingRecoverFirstDT { get; set; }
	    public virtual DateTime? QueryReusingRecoverLastDT { get; set; }
	}

    /// <summary>
    /// A class which represents the TicketHierarchyInfoOpWarnings table.
    /// </summary>
	[Table("TicketHierarchyInfoOpWarnings")]
	public partial class TicketHierarchyInfoOpWarning
	{
		[Key]
	    public virtual string RequestId { get; set; }
		[Key]
	    public virtual long EventId { get; set; }
	    public virtual int OperationWarningNo { get; set; }
	    public virtual string OperationWarning { get; set; }
	}

    /// <summary>
    /// A class which represents the TicketHierarchyInfoSsccUp table.
    /// </summary>
	[Table("TicketHierarchyInfoSsccUp")]
	public partial class TicketHierarchyInfoSsccUp
	{
		[Key]
	    public virtual string RequestId { get; set; }
		[Key]
	    public virtual long EventId { get; set; }
		[Key]
	    public virtual int NodeNo { get; set; }
	    public virtual string Sscc { get; set; }
	    public virtual DateTime? PackingDate { get; set; }
	    public virtual string ParentSscc { get; set; }
	}

    /// <summary>
    /// A class which represents the TicketHierarchyInfoSsccDown table.
    /// </summary>
	[Table("TicketHierarchyInfoSsccDown")]
	public partial class TicketHierarchyInfoSsccDown
	{
		[Key]
	    public virtual string RequestId { get; set; }
		[Key]
	    public virtual long EventId { get; set; }
		[Key]
	    public virtual int NodeNo { get; set; }
	    public virtual string Sscc { get; set; }
	    public virtual DateTime? PackingDate { get; set; }
	    public virtual string ParentSscc { get; set; }
	}

    /// <summary>
    /// A class which represents the TaskUnpackHighLevelContainer table.
    /// </summary>
	[Table("TaskUnpackHighLevelContainer")]
	public partial class TaskUnpackHighLevelContainer
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long TaskId { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string Sgtin { get; set; }
	    public virtual string Sscc { get; set; }
	    public virtual string HighLevelSscc { get; set; }
	    public virtual long? QueryKizEventId { get; set; }
	    public virtual long? UnpackEventId { get; set; }
	    public virtual string State { get; set; }
	    public virtual DateTime CreateDT { get; set; }
	    public virtual string CreateUser { get; set; }
	    public virtual DateTime? UpdateDT { get; set; }
	    public virtual string UpdateUser { get; set; }
	    public virtual string QueryKizRequestId { get; set; }
	    public virtual string UnpackRequestId { get; set; }
	}

    /// <summary>
    /// A class which represents the TicketHierarchyInfoSgtinDown table.
    /// </summary>
	[Table("TicketHierarchyInfoSgtinDown")]
	public partial class TicketHierarchyInfoSgtinDown
	{
		[Key]
	    public virtual string RequestId { get; set; }
		[Key]
	    public virtual long EventId { get; set; }
		[Key]
	    public virtual int NodeNo { get; set; }
	    public virtual string Sgtin { get; set; }
	    public virtual string Gtin { get; set; }
	    public virtual string Status { get; set; }
	    public virtual string SeriesNumber { get; set; }
	    public virtual DateTime? ExpirationDate { get; set; }
	    public virtual string Sscc { get; set; }
	}

    /// <summary>
    /// A class which represents the EventStates table.
    /// </summary>
	[Table("EventStates")]
	public partial class EventState
	{
		[Key]
	    public virtual byte EventStateId { get; set; }
	    public virtual string Name { get; set; }
	}

    /// <summary>
    /// A class which represents the EventPostings table.
    /// </summary>
	[Table("EventPostings")]
	public partial class EventPosting
	{
		[Key]
	    public virtual long EventId { get; set; }
	    public virtual string SubjectId { get; set; }
	    public virtual string ShipperInn { get; set; }
	    public virtual string ShipperKpp { get; set; }
	    public virtual DateTime? OperationDT { get; set; }
	    public virtual string DocNo { get; set; }
	    public virtual DateTime DocDT { get; set; }
	    public virtual byte? SourceType { get; set; }
	    public virtual byte? ContractType { get; set; }
	    public virtual string ContractNo { get; set; }
	}

    /// <summary>
    /// A class which represents the EventPostingDetails table.
    /// </summary>
	[Table("EventPostingDetails")]
	public partial class EventPostingDetail
	{
		[Key]
	    public virtual long EventId { get; set; }
		[Key]
	    public virtual int DetailNo { get; set; }
	    public virtual string Sgtin { get; set; }
	    public virtual decimal? Cost { get; set; }
	    public virtual decimal? VatValue { get; set; }
	}

}

